export default [
  'track_id',
  'customer_name',
  'customer_email',
  'customer_cp',
  'customer_alt_cp',
  'odp_datek',
  'odp_alternative_1',
  'odp_alternative_2',
  'id_pln',
  'address',
  'package_desc',
  'home_state',
  'additional_desc',
  'location',
  'sales_id',
]
